version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn {{cookiecutter.main_module}}.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/{{cookiecutter.main_module}}/static
      - media_volume:/home/app/web/{{cookiecutter.main_module}}/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbitmq
    restart: always
  
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  
  rabbitmq:
    image: rabbitmq:alpine
    env_file:
      - ./.env.rabbitmq
    ports:
      - 5672:5672
    restart: always

  celery:
    build:
      context: ./app
    command: celery -A {{cookiecutter.main_module}} worker -l info
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - web
    restart: always

  nginx:
    build: ./nginx-dev
    volumes:
      - static_volume:/home/app/web/{{cookiecutter.main_module}}/static
      - media_volume:/home/app/web/{{cookiecutter.main_module}}/media
    ports:
      - 8000:80
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
